// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9TEx6hYHVGU0wgNCbn7vjGRwvgm8eFk',
    appId: '1:751589005070:web:8316daef936fc203fde95f',
    messagingSenderId: '751589005070',
    projectId: 'desa-sumberkerto',
    authDomain: 'desa-sumberkerto.firebaseapp.com',
    databaseURL: 'https://desa-sumberkerto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'desa-sumberkerto.firebasestorage.app',
    measurementId: 'G-T9PHM5SP9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0B23crqZFgjroHlV4Xfj2MiNvFbJj-r4',
    appId: '1:751589005070:android:e8efdefbb960bb08fde95f',
    messagingSenderId: '751589005070',
    projectId: 'desa-sumberkerto',
    databaseURL: 'https://desa-sumberkerto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'desa-sumberkerto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUird_ZSqC7bSGB-1uCXSw0DC5bo0uidE',
    appId: '1:751589005070:ios:6f153d19f92ffa7ffde95f',
    messagingSenderId: '751589005070',
    projectId: 'desa-sumberkerto',
    databaseURL: 'https://desa-sumberkerto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'desa-sumberkerto.firebasestorage.app',
    iosBundleId: 'com.example.sumberkertoSmartVillage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUird_ZSqC7bSGB-1uCXSw0DC5bo0uidE',
    appId: '1:751589005070:ios:6f153d19f92ffa7ffde95f',
    messagingSenderId: '751589005070',
    projectId: 'desa-sumberkerto',
    databaseURL: 'https://desa-sumberkerto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'desa-sumberkerto.firebasestorage.app',
    iosBundleId: 'com.example.sumberkertoSmartVillage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf9TEx6hYHVGU0wgNCbn7vjGRwvgm8eFk',
    appId: '1:751589005070:web:0b4f7bdb86c521dbfde95f',
    messagingSenderId: '751589005070',
    projectId: 'desa-sumberkerto',
    authDomain: 'desa-sumberkerto.firebaseapp.com',
    databaseURL: 'https://desa-sumberkerto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'desa-sumberkerto.firebasestorage.app',
    measurementId: 'G-TWCQBV8HDW',
  );
}
