import 'dart:io';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:image_picker/image_picker.dart';
import 'package:sumberkerto_smart_village/app/data/models/news_model.dart';
import 'package:sumberkerto_smart_village/app/data/services/media_compression_service.dart';
import 'package:sumberkerto_smart_village/app/routes/app_pages.dart';
import 'package:sumberkerto_smart_village/app/utils/snackbar_utils.dart';
import 'package:image/image.dart' as img;

class EditnewsController extends GetxController {
  final DatabaseReference _database = FirebaseDatabase.instance.ref();
  final FirebaseStorage _storage = FirebaseStorage.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final GetStorage _storage2 = GetStorage();
  final ImagePicker _picker = ImagePicker();

  // Form controllers
  final titleController = TextEditingController();
  final descriptionController = TextEditingController();
  final locationController = TextEditingController();
  final categoryController = TextEditingController();

  // Media files (new uploads)
  final bannerImage = Rxn<File>();
  final images = <File>[].obs;
  final videoFile = Rxn<File>();
  final videoThumbnail = Rxn<File>();

  // Existing media URLs dari database
  final existingBannerUrl = Rxn<String>();
  final existingImageUrls = <String>[].obs;
  final existingVideoUrl = Rxn<String>();
  final existingVideoThumbnailUrl = Rxn<String>();

  // Selected category & tags
  final selectedCategory = ''.obs;
  final autoGeneratedTags = <String>[].obs;

  // Available categories - Top 5 from database
  final availableCategories = <String>[].obs;

  // Category suggestions based on input
  final categorySuggestions = <String>[].obs;
  final showCategorySuggestions = false.obs;

  // Location suggestions
  final locationSuggestions = <String>[].obs;
  final showLocationSuggestions = false.obs;
  final detectedLocation = Rxn<String>();

  // Common locations in Indonesia (expanded)
  final commonLocations = <String>[
    // Jawa Timur
    'Malang, Jawa Timur',
    'Surabaya, Jawa Timur',
    'Batu, Jawa Timur',
    'Blitar, Jawa Timur',
    'Kediri, Jawa Timur',
    'Jember, Jawa Timur',
    'Probolinggo, Jawa Timur',
    'Pasuruan, Jawa Timur',
    'Mojokerto, Jawa Timur',
    'Madiun, Jawa Timur',

    // Jawa Tengah
    'Semarang, Jawa Tengah',
    'Solo, Jawa Tengah',
    'Yogyakarta, DI Yogyakarta',
    'Magelang, Jawa Tengah',
    'Salatiga, Jawa Tengah',
    'Tegal, Jawa Tengah',
    'Pekalongan, Jawa Tengah',

    // Jawa Barat
    'Bandung, Jawa Barat',
    'Bogor, Jawa Barat',
    'Bekasi, Jawa Barat',
    'Depok, Jawa Barat',
    'Cirebon, Jawa Barat',
    'Tasikmalaya, Jawa Barat',
    'Sukabumi, Jawa Barat',

    // Jakarta & sekitarnya
    'Jakarta Pusat, DKI Jakarta',
    'Jakarta Selatan, DKI Jakarta',
    'Jakarta Utara, DKI Jakarta',
    'Jakarta Barat, DKI Jakarta',
    'Jakarta Timur, DKI Jakarta',
    'Tangerang, Banten',
    'Tangerang Selatan, Banten',
    'Serang, Banten',

    // Sumatera
    'Medan, Sumatera Utara',
    'Palembang, Sumatera Selatan',
    'Padang, Sumatera Barat',
    'Pekanbaru, Riau',
    'Bandar Lampung, Lampung',
    'Jambi, Jambi',
    'Bengkulu, Bengkulu',
    'Banda Aceh, Aceh',

    // Kalimantan
    'Balikpapan, Kalimantan Timur',
    'Samarinda, Kalimantan Timur',
    'Banjarmasin, Kalimantan Selatan',
    'Pontianak, Kalimantan Barat',
    'Palangkaraya, Kalimantan Tengah',

    // Sulawesi
    'Makassar, Sulawesi Selatan',
    'Manado, Sulawesi Utara',
    'Palu, Sulawesi Tengah',
    'Kendari, Sulawesi Tenggara',
    'Gorontalo, Gorontalo',

    // Bali & Nusa Tenggara
    'Denpasar, Bali',
    'Mataram, Nusa Tenggara Barat',
    'Kupang, Nusa Tenggara Timur',

    // Maluku & Papua
    'Ambon, Maluku',
    'Ternate, Maluku Utara',
    'Jayapura, Papua',
    'Sorong, Papua Barat',
  ];

  // All categories database (untuk suggestions)
  final allCategories = <String>[].obs;

  // Loading states
  final isUploading = false.obs;
  final uploadProgress = 0.0.obs;
  final isCompressing = false.obs;

  // Edit mode
  final isEditMode = false.obs;
  NewsModel? editingNews;

  @override
  void onInit() {
    super.onInit();

    // Location search listener
    locationController.addListener(_onLocationChanged);

    // Category search listener
    categoryController.addListener(_onCategoryChanged);

    // Fetch available categories
    fetchCategories();

    // Fetch all categories for suggestions
    fetchAllCategories();

    // Check if editing existing news
    if (Get.arguments != null && Get.arguments is NewsModel) {
      editingNews = Get.arguments as NewsModel;
      isEditMode.value = true;
      _loadEditData();
    }
  }

  @override
  void onClose() {
    titleController.dispose();
    descriptionController.dispose();
    locationController.dispose();
    categoryController.dispose();
    MediaCompressionService.cleanupTemporary();
    super.onClose();
  }

  /// Get current user data from GetStorage
  String? get _currentUserId {
    return _storage2.read('userId') ?? _auth.currentUser?.uid;
  }

  /// Fetch top 5 categories from database
  Future<void> fetchCategories() async {
    try {
      final snapshot = await _database.child('news').get();

      if (snapshot.exists) {
        final data = snapshot.value as Map<dynamic, dynamic>;
        final Map<String, int> categoryCount = {};

        // Count category occurrences
        data.forEach((key, value) {
          if (value is Map && value['category'] != null) {
            final category = value['category'] as String;
            categoryCount[category] = (categoryCount[category] ?? 0) + 1;
          }
        });

        // Sort by count and take top 5
        final sortedCategories = categoryCount.entries.toList()
          ..sort((a, b) => b.value.compareTo(a.value));

        availableCategories.value = sortedCategories
            .take(5)
            .map((e) => e.key)
            .toList();
      }
    } catch (e) {
      print('Error fetching categories: $e');
    }
  }

  /// Fetch all categories for suggestions
  Future<void> fetchAllCategories() async {
    try {
      final snapshot = await _database.child('news').get();

      if (snapshot.exists) {
        final data = snapshot.value as Map<dynamic, dynamic>;
        final Set<String> categories = {};

        // Collect all unique categories
        data.forEach((key, value) {
          if (value is Map && value['category'] != null) {
            categories.add(value['category'] as String);
          }
          // Also collect from tags
          if (value is Map && value['tags'] != null) {
            final tags = value['tags'];
            if (tags is List) {
              categories.addAll(tags.map((t) => t.toString()));
            }
          }
        });

        allCategories.value = categories.toList()..sort();
      }
    } catch (e) {
      print('Error fetching all categories: $e');
    }
  }

  /// Load data for editing
  void _loadEditData() {
    if (editingNews == null) return;

    titleController.text = editingNews!.title;
    descriptionController.text = editingNews!.description;
    locationController.text = editingNews!.location ?? '';

    if (editingNews!.tags.isNotEmpty) {
      selectedCategory.value = editingNews!.tags.first;
      categoryController.text = editingNews!.tags.first;

      // Load existing tags
      autoGeneratedTags.value = List<String>.from(editingNews!.tags);
    }

    // Load existing media URLs
    if (editingNews!.bannerImage != null &&
        editingNews!.bannerImage!.isNotEmpty) {
      existingBannerUrl.value = editingNews!.bannerImage;
    }

    if (editingNews!.images.isNotEmpty) {
      existingImageUrls.value = List<String>.from(editingNews!.images);
    }

    if (editingNews!.videoUrl != null && editingNews!.videoUrl!.isNotEmpty) {
      existingVideoUrl.value = editingNews!.videoUrl;
      if (editingNews!.videoThumbnail != null &&
          editingNews!.videoThumbnail!.isNotEmpty) {
        existingVideoThumbnailUrl.value = editingNews!.videoThumbnail;
      }
    }
  }

  /// Category search with suggestions
  void _onCategoryChanged() {
    final query = categoryController.text.trim();

    if (query.isEmpty) {
      showCategorySuggestions.value = false;
      categorySuggestions.clear();
      return;
    }

    // Filter categories based on query
    final filtered = allCategories
        .where((cat) => cat.toLowerCase().contains(query.toLowerCase()))
        .toList();

    if (filtered.isNotEmpty) {
      categorySuggestions.value = filtered.take(5).toList();
      showCategorySuggestions.value = true;
    } else {
      categorySuggestions.clear();
      showCategorySuggestions.value = false;
    }

    // Auto-generate tags based on input
    _generateTagsFromText(query);
  }

  /// Location search
  void _onLocationChanged() {
    final query = locationController.text.trim();

    if (query.isEmpty) {
      showLocationSuggestions.value = false;
      locationSuggestions.clear();
      return;
    }

    // Filter locations based on query
    final filtered = commonLocations
        .where((loc) => loc.toLowerCase().contains(query.toLowerCase()))
        .toList();

    if (filtered.isNotEmpty) {
      locationSuggestions.value = filtered;
      showLocationSuggestions.value = true;
    } else {
      locationSuggestions.clear();
      showLocationSuggestions.value = false;
    }
  }

  /// Select location from suggestions
  void selectLocation(String location) {
    locationController.text = location;
    showLocationSuggestions.value = false;
    locationSuggestions.clear();
  }

  /// Select category
  void selectCategory(String category) {
    selectedCategory.value = category;
    categoryController.text = category;
    showCategorySuggestions.value = false;

    // Add to tags if not already present
    if (!autoGeneratedTags.contains(category)) {
      autoGeneratedTags.add(category);
    }
  }

  /// Select category from suggestions
  void selectCategorySuggestion(String category) {
    selectCategory(category);
  }

  /// Set category from manual input
  void setManualCategory() {
    final category = categoryController.text.trim();
    if (category.isNotEmpty) {
      selectedCategory.value = category;
      if (!autoGeneratedTags.contains(category)) {
        autoGeneratedTags.add(category);
      }
    }
  }

  /// Generate tags automatically from title and description
  void _generateTagsFromText(String text) {
    final keywords = _extractKeywords(text);

    // Clear and regenerate tags
    final newTags = <String>{};

    // Add main category
    if (selectedCategory.value.isNotEmpty) {
      newTags.add(selectedCategory.value);
    }

    // Add current input if not empty
    if (text.isNotEmpty) {
      newTags.add(text);
    }

    // Add keywords
    newTags.addAll(keywords);

    // Limit to 5 tags
    autoGeneratedTags.value = newTags.take(5).toList();
  }

  /// Auto-generate tags from title and description
  void generateAutoTags() {
    final title = titleController.text.trim();
    final description = descriptionController.text.trim();
    final combinedText = '$title $description';

    final keywords = _extractKeywords(combinedText);

    final newTags = <String>{};

    // Add main category
    if (selectedCategory.value.isNotEmpty) {
      newTags.add(selectedCategory.value);
    }

    // Add keywords
    newTags.addAll(keywords);

    // Limit to 5 tags
    autoGeneratedTags.value = newTags.take(5).toList();
  }

  /// Extract keywords from text
  List<String> _extractKeywords(String text) {
    // Common Indonesian stop words
    final stopWords = {
      'yang',
      'dan',
      'di',
      'ke',
      'dari',
      'ini',
      'itu',
      'dengan',
      'untuk',
      'pada',
      'adalah',
      'oleh',
      'dalam',
      'akan',
      'telah',
      'ada',
      'atau',
      'juga',
      'sebagai',
      'seperti',
      'karena',
      'namun',
      'tetapi',
      'jika',
      'maka',
      'saat',
      'ketika',
      'sehingga',
      'tersebut',
      'lebih',
      'dapat',
      'harus',
      'sudah',
      'bisa',
      'tidak',
      'belum',
      'masih',
      'sangat',
      'sekali',
    };

    // Split and clean text
    final words = text
        .toLowerCase()
        .split(RegExp(r'\s+'))
        .where((word) => word.length > 3 && !stopWords.contains(word))
        .toList();

    // Count word frequency
    final wordCount = <String, int>{};
    for (var word in words) {
      wordCount[word] = (wordCount[word] ?? 0) + 1;
    }

    // Sort by frequency and take top words
    final sortedWords = wordCount.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    return sortedWords.take(3).map((e) => e.key).toList();
  }

  /// Remove tag
  void removeTag(String tag) {
    autoGeneratedTags.remove(tag);
  }

  /// Add custom tag
  void addCustomTag(String tag) {
    final trimmedTag = tag.trim();
    if (trimmedTag.isNotEmpty && !autoGeneratedTags.contains(trimmedTag)) {
      autoGeneratedTags.add(trimmedTag);
    }
  }

  Future<void> extractLocationFromImage(File imageFile) async {
    try {
      final bytes = await imageFile.readAsBytes();
      final decoded = img.decodeImage(bytes);
      if (decoded == null) return;

      // Cara baru mengakses EXIF data di image ^4.7.2
      final exifData = decoded.exif;
      if (exifData.isEmpty) return;

      // Akses data GPS menggunakan key langsung
      final latTag = exifData['GPS GPSLatitude'];
      final lonTag = exifData['GPS GPSLongitude'];
      final latRef = exifData['GPS GPSLatitudeRef'];
      final lonRef = exifData['GPS GPSLongitudeRef'];

      if (latTag == null || lonTag == null) return;

      // Parse koordinat
      double? latitude = _parseGpsCoordinate(latTag);
      double? longitude = _parseGpsCoordinate(lonTag);

      if (latitude == null || longitude == null) return;

      // Terapkan referensi arah (N/S/E/W)
      if (latRef != null && latRef.toString().toUpperCase() == 'S') {
        latitude = -latitude;
      }
      if (lonRef != null && lonRef.toString().toUpperCase() == 'W') {
        longitude = -longitude;
      }

      if (_isValidCoordinate(latitude, longitude)) {
        final locationName = _getIndonesiaRegion(latitude, longitude);
        if (locationName != null) {
          locationController.text = locationName;
          detectedLocation.value = locationName;
        }
      }
    } catch (e) {
      print('EXIF extraction error: $e');
    }
  }

  /// Parse GPS coordinate from EXIF format
  double? _parseGpsCoordinate(dynamic gpsData) {
    if (gpsData == null) return null;

    try {
      // GPS data biasanya dalam format: [degrees, minutes, seconds]
      if (gpsData is List && gpsData.length >= 3) {
        final degrees = _parseRational(gpsData[0]);
        final minutes = _parseRational(gpsData[1]);
        final seconds = _parseRational(gpsData[2]);

        if (degrees != null && minutes != null && seconds != null) {
          return degrees + (minutes / 60.0) + (seconds / 3600.0);
        }
      }

      // Jika sudah dalam format decimal
      if (gpsData is double) return gpsData;
      if (gpsData is int) return gpsData.toDouble();

      return null;
    } catch (e) {
      print('Error parsing GPS coordinate: $e');
      return null;
    }
  }

  /// Parse rational number (numerator/denominator)
  double? _parseRational(dynamic value) {
    if (value is double) return value;
    if (value is int) return value.toDouble();

    try {
      if (value is String) {
        if (value.contains('/')) {
          final parts = value.split('/');
          if (parts.length == 2) {
            final numerator = double.parse(parts[0]);
            final denominator = double.parse(parts[1]);
            if (denominator != 0) {
              return numerator / denominator;
            }
          }
        }
        return double.parse(value);
      }

      if (value is List && value.length == 2) {
        final numerator = value[0] as num;
        final denominator = value[1] as num;
        if (denominator != 0) {
          return numerator / denominator;
        }
      }
    } catch (e) {
      print('Error parsing rational: $e');
    }

    return null;
  }

  /// Validate GPS coordinates
  bool _isValidCoordinate(double? latitude, double? longitude) {
    if (latitude == null || longitude == null) return false;

    // Valid latitude: -90 to 90
    // Valid longitude: -180 to 180
    return latitude >= -90 &&
        latitude <= 90 &&
        longitude >= -180 &&
        longitude <= 180;
  }

  /// Get Indonesia region from coordinates (rough estimation)
  String? _getIndonesiaRegion(double latitude, double longitude) {
    // Rough boundaries untuk region Indonesia

    // Jakarta area
    if (latitude >= -6.3 &&
        latitude <= -6.0 &&
        longitude >= 106.7 &&
        longitude <= 107.0) {
      return 'Jakarta, DKI Jakarta';
    }

    // Surabaya area
    if (latitude >= -7.5 &&
        latitude <= -7.0 &&
        longitude >= 112.5 &&
        longitude <= 113.0) {
      return 'Surabaya, Jawa Timur';
    }

    // Malang area
    if (latitude >= -8.2 &&
        latitude <= -7.8 &&
        longitude >= 112.5 &&
        longitude <= 112.8) {
      return 'Malang, Jawa Timur';
    }

    // Bandung area
    if (latitude >= -7.0 &&
        latitude <= -6.8 &&
        longitude >= 107.5 &&
        longitude <= 107.8) {
      return 'Bandung, Jawa Barat';
    }

    // Semarang area
    if (latitude >= -7.2 &&
        latitude <= -6.9 &&
        longitude >= 110.3 &&
        longitude <= 110.6) {
      return 'Semarang, Jawa Tengah';
    }

    // Yogyakarta area
    if (latitude >= -8.0 &&
        latitude <= -7.7 &&
        longitude >= 110.3 &&
        longitude <= 110.5) {
      return 'Yogyakarta, DI Yogyakarta';
    }

    // Bali area
    if (latitude >= -8.8 &&
        latitude <= -8.3 &&
        longitude >= 115.0 &&
        longitude <= 115.3) {
      return 'Denpasar, Bali';
    }

    // Medan area
    if (latitude >= 3.5 &&
        latitude <= 3.6 &&
        longitude >= 98.6 &&
        longitude <= 98.7) {
      return 'Medan, Sumatera Utara';
    }

    // Makassar area
    if (latitude >= -5.2 &&
        latitude <= -5.0 &&
        longitude >= 119.4 &&
        longitude <= 119.5) {
      return 'Makassar, Sulawesi Selatan';
    }

    // General regions based on coordinates
    if (latitude >= -9 &&
        latitude <= -5 &&
        longitude >= 106 &&
        longitude <= 115) {
      return 'Jawa'; // General Java region
    }

    if (latitude >= -9 &&
        latitude <= -8 &&
        longitude >= 115 &&
        longitude <= 116) {
      return 'Bali';
    }

    if (latitude >= 0 && latitude <= 6 && longitude >= 95 && longitude <= 106) {
      return 'Sumatera';
    }

    if (latitude >= -6 &&
        latitude <= 2 &&
        longitude >= 108 &&
        longitude <= 119) {
      return 'Kalimantan';
    }

    if (latitude >= -6 &&
        latitude <= 2 &&
        longitude >= 119 &&
        longitude <= 125) {
      return 'Sulawesi';
    }

    // Default: can't determine specific location
    return null;
  }

  /// Pick banner image
  Future<void> pickBannerImage(BuildContext context) async {
    try {
      final XFile? image = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 85,
      );

      if (image != null) {
        isCompressing.value = true;
        final File imageFile = File(image.path);

        // Extract location from image metadata
        await extractLocationFromImage(imageFile);

        final compressed = await MediaCompressionService.compressImage(
          imageFile,
        );

        if (compressed != null) {
          bannerImage.value = compressed;
          // Clear existing banner when new one is uploaded
          existingBannerUrl.value = null;
          context.showSuccessSnackBar('Banner berhasil dipilih');
        }
        isCompressing.value = false;
      }
    } catch (e) {
      isCompressing.value = false;
      context.showErrorSnackBar('Gagal memilih gambar');
    }
  }

  /// Pick images (max 2 total)
  Future<void> pickImages(BuildContext context) async {
    try {
      final totalImages = existingImageUrls.length + images.length;

      if (totalImages >= 2) {
        context.showWarningSnackBar('Maksimal 2 gambar');
        return;
      }

      final List<XFile> pickedImages = await _picker.pickMultiImage(
        imageQuality: 85,
      );

      if (pickedImages.isNotEmpty) {
        isCompressing.value = true;

        for (var image in pickedImages) {
          final currentTotal = existingImageUrls.length + images.length;
          if (currentTotal >= 2) break;

          final File imageFile = File(image.path);

          // Extract location from first image if location is empty
          if (locationController.text.trim().isEmpty && images.isEmpty) {
            await extractLocationFromImage(imageFile);
          }

          final compressed = await MediaCompressionService.compressImage(
            imageFile,
          );

          if (compressed != null) {
            images.add(compressed);
          }
        }

        isCompressing.value = false;
        context.showSuccessSnackBar('${images.length} gambar dipilih');
      }
    } catch (e) {
      isCompressing.value = false;
      context.showErrorSnackBar('Gagal memilih gambar');
    }
  }

  /// Remove new image
  void removeImage(int index) {
    if (index >= 0 && index < images.length) {
      images.removeAt(index);
    }
  }

  /// Remove existing image
  void removeExistingImage(int index) {
    if (index >= 0 && index < existingImageUrls.length) {
      existingImageUrls.removeAt(index);
    }
  }

  /// Remove new banner
  void removeBanner() {
    bannerImage.value = null;
  }

  /// Remove existing banner
  void removeExistingBanner() {
    existingBannerUrl.value = null;
  }

  /// Pick video
  Future<void> pickVideo(BuildContext context) async {
    try {
      final XFile? video = await _picker.pickVideo(
        source: ImageSource.gallery,
        maxDuration: const Duration(minutes: 2),
      );

      if (video != null) {
        isCompressing.value = true;
        context.showInfoSnackBar('Mengompress video...');

        final File videoFileTemp = File(video.path);

        // Compress video
        final compressed = await MediaCompressionService.compressVideo(
          videoFileTemp,
        );

        if (compressed != null) {
          videoFile.value = compressed;

          // Clear existing video when new one is uploaded
          existingVideoUrl.value = null;
          existingVideoThumbnailUrl.value = null;

          // Generate thumbnail
          final thumbnail =
              await MediaCompressionService.generateVideoThumbnail(compressed);
          videoThumbnail.value = thumbnail;

          final size = await compressed.length();
          context.showSuccessSnackBar(
            'Video dikompress ke ${(size / 1024 / 1024).toStringAsFixed(2)} MB',
          );
        }

        isCompressing.value = false;
      }
    } catch (e) {
      isCompressing.value = false;
      context.showErrorSnackBar('Gagal memilih video');
    }
  }

  /// Remove new video
  void removeVideo() {
    videoFile.value = null;
    videoThumbnail.value = null;
  }

  /// Remove existing video
  void removeExistingVideo() {
    existingVideoUrl.value = null;
    existingVideoThumbnailUrl.value = null;
  }

  /// Upload file to Firebase Storage
  Future<String?> _uploadFile(File file, String folder, String fileName) async {
    try {
      final ref = _storage.ref().child('$folder/$fileName');
      final uploadTask = ref.putFile(file);

      uploadTask.snapshotEvents.listen((TaskSnapshot snapshot) {
        uploadProgress.value = snapshot.bytesTransferred / snapshot.totalBytes;
      });

      await uploadTask;
      final downloadUrl = await ref.getDownloadURL();

      return downloadUrl;
    } catch (e) {
      print('Error uploading file: $e');
      return null;
    }
  }

  /// Validate form
  bool _validateForm(BuildContext context) {
    if (titleController.text.trim().isEmpty) {
      context.showErrorSnackBar('Judul tidak boleh kosong');
      return false;
    }

    if (descriptionController.text.trim().isEmpty) {
      context.showErrorSnackBar('Deskripsi tidak boleh kosong');
      return false;
    }

    if (selectedCategory.value.isEmpty) {
      context.showErrorSnackBar('Kategori tidak boleh kosong');
      return false;
    }

    // Check if there's any media (existing or new)
    final hasMedia =
        bannerImage.value != null ||
        existingBannerUrl.value != null ||
        images.isNotEmpty ||
        existingImageUrls.isNotEmpty ||
        videoFile.value != null ||
        existingVideoUrl.value != null;

    if (!hasMedia && !isEditMode.value) {
      context.showErrorSnackBar('Tambahkan minimal satu media');
      return false;
    }

    return true;
  }

  /// Submit news
  Future<void> submitNews(BuildContext context) async {
    // Set category from input before validation
    setManualCategory();

    // Auto-generate tags if empty
    if (autoGeneratedTags.isEmpty) {
      generateAutoTags();
    }

    if (!_validateForm(context)) return;

    try {
      isUploading.value = true;
      uploadProgress.value = 0.0;

      final userId = _currentUserId;
      if (userId == null) {
        context.showErrorSnackBar('Pengguna tidak terautentikasi');
        isUploading.value = false;
        return;
      }

      // Fetch username from database
      String userName = 'Anonymous';
      try {
        userName = _storage2.read('userName') ?? _storage2.read('name') ?? '';

        if (userName.isEmpty) {
          print('Fetching username from database for userId: $userId');
          final userSnapshot = await _database
              .child('users/$userId/name')
              .get();

          if (userSnapshot.exists && userSnapshot.value != null) {
            userName = userSnapshot.value.toString();
            _storage2.write('userName', userName);
            print('Username fetched from database: $userName');
          } else {
            print('No username found in database, using Anonymous');
            userName = 'Anonymous';
          }
        }
      } catch (e) {
        print('Error fetching username: $e');
        userName = 'Anonymous';
      }

      final timestamp = DateTime.now();

      // Generate news ID
      final newsRef = isEditMode.value
          ? _database.child('news/${editingNews!.id}')
          : _database.child('news').push();

      final newsId = newsRef.key!;

      String? bannerUrl;
      List<String> imageUrls = [];
      String? videoUrl;
      String? videoThumbnailUrl;

      // Handle banner - new upload or existing
      if (bannerImage.value != null) {
        // New banner uploaded
        bannerUrl = await _uploadFile(
          bannerImage.value!,
          'news/banners',
          '${newsId}_banner_${timestamp.millisecondsSinceEpoch}.jpg',
        );
      } else if (existingBannerUrl.value != null) {
        // Keep existing banner
        bannerUrl = existingBannerUrl.value;
      }

      // Handle images - combine existing and new
      // First, add existing images that weren't removed
      imageUrls.addAll(existingImageUrls);

      // Then upload new images
      for (int i = 0; i < images.length; i++) {
        final url = await _uploadFile(
          images[i],
          'news/images',
          '${newsId}_image_${existingImageUrls.length + i}_${timestamp.millisecondsSinceEpoch}.jpg',
        );
        if (url != null) {
          imageUrls.add(url);
        }
      }

      // Handle video - new upload or existing
      if (videoFile.value != null) {
        // New video uploaded
        videoUrl = await _uploadFile(
          videoFile.value!,
          'news/videos',
          '${newsId}_video_${timestamp.millisecondsSinceEpoch}.mp4',
        );

        if (videoThumbnail.value != null) {
          videoThumbnailUrl = await _uploadFile(
            videoThumbnail.value!,
            'news/thumbnails',
            '${newsId}_thumbnail_${timestamp.millisecondsSinceEpoch}.jpg',
          );
        }
      } else if (existingVideoUrl.value != null) {
        // Keep existing video
        videoUrl = existingVideoUrl.value;
        videoThumbnailUrl = existingVideoThumbnailUrl.value;
      }

      // Prepare tags - ensure main category is first
      final finalTags = <String>[];
      if (selectedCategory.value.isNotEmpty) {
        finalTags.add(selectedCategory.value);
      }
      for (var tag in autoGeneratedTags) {
        if (!finalTags.contains(tag)) {
          finalTags.add(tag);
        }
      }

      // Create news data with fetched username
      final newsData = {
        'title': titleController.text.trim(),
        'description': descriptionController.text.trim(),
        'created_by': userName,
        'user_id': userId,
        'created_at': isEditMode.value
            ? editingNews!.createdAt.millisecondsSinceEpoch
            : timestamp.millisecondsSinceEpoch,
        'category': selectedCategory.value,
        'tags': finalTags,
        'location': locationController.text.trim().isEmpty
            ? null
            : locationController.text.trim(),
        'banner_image': bannerUrl,
        'images': imageUrls,
        'video_url': videoUrl,
        'video_thumbnail': videoThumbnailUrl,
        'view_count': isEditMode.value ? editingNews!.viewCount : 0,
        'like_count': isEditMode.value ? editingNews!.likeCount : 0,
      };

      print('Saving news with username: $userName');
      print('Tags: $finalTags');

      // Save to Realtime Database
      await newsRef.set(newsData);

      isUploading.value = false;
      uploadProgress.value = 0.0;

      context.showSuccessSnackBar(
        isEditMode.value
            ? 'Berita berhasil diperbarui!'
            : 'Berita berhasil dipublikasikan!',
      );

      // Wait a bit for snackbar to show then navigate
      await Future.delayed(const Duration(milliseconds: 500));

      // Navigate back to news view
      Get.offAllNamed(Routes.NEWS);
    } catch (e) {
      isUploading.value = false;
      uploadProgress.value = 0.0;

      print('Error saving news: $e');
      context.showErrorSnackBar('Gagal menyimpan berita: $e');
    }
  }
}
